before:
  hooks:
    - go mod download
builds:
  - #
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
