name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Prepare
        run: |
          sudo apt update -qq
          sudo apt install -y -qq libpcap-dev

      - name: Binaries Release
        uses: goreleaser/goreleaser-action@v2.1.0
        with:
          version: v0.138.0
          args: -f .goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

  release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Prepare
        run: |
          Import-Module BitsTransfer
          Start-BitsTransfer -Source https://www.dropbox.com/s/1oe616ya866vc7g/wpcap.dll?dl=1 -Destination $env:WINDIR\system32\wpcap.dll

      - name: Binaries Release
        uses: goreleaser/goreleaser-action@v2.1.0
        with:
          version: v0.138.0
          args: -f .goreleaser-windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
